# Generated by Django 6.0 on 2025-12-15 14:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('idPelicula', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(verbose_name='Título')),
                ('fecha', models.DateField(verbose_name='Fecha de Estreno')),
                ('director', models.TextField(verbose_name='Director')),
                ('actoresPrincipales', models.TextField(verbose_name='Actores Principales')),
            ],
            options={
                'ordering': ('titulo',),
            },
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.IntegerField(verbose_name='ID Usuario')),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)], verbose_name='Puntuación')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pelicula')),
            ],
            options={
                'ordering': ('idUsuario', 'pelicula'),
                'unique_together': {('idUsuario', 'pelicula')},
            },
        ),
    ]
